### ISSUE TITLE
Admin plugin assumes arguments are valid

### ISSUE THREAD

**Issue by Link2006** [hugeblank/BetaBot#1]
There's a few issues with the plugin as it does not make sure all 3 arguments are set, nor if the level is a valid number 

Replication: Do a fresh install, type "!admin set yourname" in chat, confirm yourself, try to use admin commands.
Result: unable to use admin commands, no admins set and unable to add another one.

Affected Line: https://github.com/hugeblank/BetaBot/blob/master/BetaBot/commands/admin.lua#L7

**Comment by hugeblank** [comment]
I'm pretty this was fixed when I moved it to Allium. I didn't even realize this was still here. XP
